### ISSUE TITLE
adsbexchange-978 support

### ISSUE THREAD

**Issue by kdknigga** [adsbxchange/adsbexchange-stats#23]
Hi,

It looks like this script only bothers with gathering stats for adsbexchange-feed, not adsbexchange-978, unless 978 stats get funneled back into /run/adsbexchange-feed somehow and I'm just not seeing that.

I'm considering adding 978 support.  Would you be interested in that?  If so, do you have any preferences on how you'd like to see that accomplished?  Right now the script processes the first stats source it finds.  Maybe it could process all of the valid sources it finds instead of just the first?  Or, perhaps, multiple instances of adsbexchange-stats could run using [systemd template units](https://fedoramagazine.org/systemd-template-unit-files/)?

Thanks

**Comment by wiedehopf** [comment]
If you run the image ... the feed is combined anyhow and the stats is made from that.

Otherwise the 978 will be an insignificant number of aircraft.
We'd ask that you just graph that locally as we don't plan adding that complication to the current system .. which might not be permanent anyhow.

graphs1090 should work fine for graphing locally.

**Comment by kdknigga** [comment]
Thanks.
